CREATE SEQUENCE SEQUENCE_NOTIF_CUST_TMPL_ID       INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER;
CREATE SEQUENCE SEQUENCE_STAF_NOTIF_TMPL_ID       INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER;
CREATE SEQUENCE SEQUENCE_NTF_CUST_TMPL_APPLY_ID INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER;
CREATE SEQUENCE SEQUENCE_NTF_TMPL_TAG_ID INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER;
CREATE SEQUENCE SEQUENCE_NTF_TMPL_CHNL_ID INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER;
CREATE SEQUENCE SEQUENCE_NTF_TMPL_LNG_ID INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER;

CREATE TABLE "NTF_TMPL_TAG"
(
    "ID" NUMBER(22,0) DEFAULT "SEQUENCE_NTF_TMPL_TAG_ID"."NEXTVAL" NOT NULL ENABLE,
    "NAME" VARCHAR2(64) NOT NULL ENABLE,
    "CREATED_BY" VARCHAR2(100),
    "CREATED_TIME" TIMESTAMP (6),
    "LAST_UPDATED_BY" VARCHAR2(100),
    "LAST_UPDATED_TIME" TIMESTAMP (6)
);

CREATE TABLE "NTF_TMPL_CHNL"
(
    "ID" NUMBER(22,0) DEFAULT "SEQUENCE_NTF_TMPL_CHNL_ID"."NEXTVAL" NOT NULL ENABLE,
    "CHNL_TYPE" VARCHAR2(32) NOT NULL ENABLE,
    "CHNL_NAME" VARCHAR2(64) NOT NULL ENABLE,
    "CREATED_BY" VARCHAR2(100),
    "CREATED_TIME" TIMESTAMP (6),
    "LAST_UPDATED_BY" VARCHAR2(100),
    "LAST_UPDATED_TIME" TIMESTAMP (6)
);

CREATE TABLE "NTF_TMPL_LNG"
(
    "ID" NUMBER(22,0) DEFAULT "SEQUENCE_NTF_TMPL_LNG_ID"."NEXTVAL" NOT NULL ENABLE,
    "CODE" VARCHAR2(32) NOT NULL ENABLE,
    "DESC" VARCHAR2(64) NOT NULL ENABLE,
    "CREATED_BY" VARCHAR2(100),
    "CREATED_TIME" TIMESTAMP (6),
    "LAST_UPDATED_BY" VARCHAR2(100),
    "LAST_UPDATED_TIME" TIMESTAMP (6)
);

CREATE TABLE NTF_CUST_TMPL (
                          ID          NUMBER(22,0) DEFAULT "SEQUENCE_NOTIF_CUST_TMPL_ID"."NEXTVAL" NOT NULL ENABLE,
                          TMPL_CODE   VARCHAR2(100),
                          TMPL_ID     VARCHAR2(100),
                          CHNL_TYPE   VARCHAR2(100),
                          LANGUAGE   VARCHAR2(100),
                          APPLY_TO      VARCHAR2(100),
                          TMPL_DESC     VARCHAR2(1024),
                          TMPL_TXT    CLOB,
                          TMPL_CONFIG CLOB,
                          EFFECTIVE_DATE TIMESTAMP(6),
                          EXPIRY_DATE    TIMESTAMP(6),
                          TOPIC       VARCHAR2(100) NULL,
                          EVT_TYPE    VARCHAR2(100) NULL,
                          STS_CD      VARCHAR2(50),
                          VER_NBR     NUMBER(10),
                          "CREATED_BY" VARCHAR2(100),
                          "CREATED_TIME" TIMESTAMP (6),
                          "LAST_UPDATED_BY" VARCHAR2(100),
                          "LAST_UPDATED_TIME" TIMESTAMP (6),
                          CONSTRAINT ntf_cust_tmpl_pkey PRIMARY KEY (TMPL_CODE)
);

CREATE TABLE "NTF_CUST_TMPL_APPLY"
(
    "ID" NUMBER(22,0) DEFAULT "SEQUENCE_NTF_CUST_TMPL_APPLY_ID"."NEXTVAL" NOT NULL ENABLE,
    "CODE" VARCHAR2(32) NOT NULL ENABLE,
    "DESC" VARCHAR2(64) NOT NULL ENABLE,
    "CREATED_BY" VARCHAR2(100),
    "CREATED_TIME" TIMESTAMP (6),
    "LAST_UPDATED_BY" VARCHAR2(100),
    "LAST_UPDATED_TIME" TIMESTAMP (6)
);

CREATE TABLE NTF_TMPL (
                          ID          NUMBER(22,0) DEFAULT "SEQUENCE_STAF_NOTIF_TMPL_ID"."NEXTVAL" NOT NULL ENABLE,
                          TMPL_CODE   VARCHAR2(100),
                          TMPL_ID     VARCHAR2(100),
                          CHNL_TYPE   VARCHAR2(100),
                          LANGUAGE   VARCHAR2(100),
                          TMPL_DESC     VARCHAR2(1024),
                          TMPL_TXT    CLOB,
                          TMPL_CONFIG CLOB,
                          TOPIC       VARCHAR2(100) NULL,
                          EVT_TYPE    VARCHAR2(100) NULL,
                          STS_CD      VARCHAR2(50),
                          VER_NBR     NUMBER(10),
                          "CREATED_BY" VARCHAR2(100),
                          "CREATED_TIME" TIMESTAMP (6),
                          "LAST_UPDATED_BY" VARCHAR2(100),
                          "LAST_UPDATED_TIME" TIMESTAMP (6),
                          CONSTRAINT ntf_tmpl_pkey PRIMARY KEY (TMPL_CODE)
);
COMMENT ON COLUMN NTF_TMPL.TMPL_CODE IS 'The unique key for template, TMPL_ID|CHNL_TYPE|LANGUAGE, such as: WORKFLOW-SUBMIT|EMAIL|EN';
COMMENT ON COLUMN NTF_TMPL.TMPL_ID IS 'The template for domain/common business without CHNL_TYPE & LANGUAGE, such as: WORKFLOW-SUBMIT';
COMMENT ON COLUMN NTF_TMPL.TMPL_TXT IS 'The actual template with json format';
COMMENT ON COLUMN NTF_TMPL.TMPL_CONFIG IS 'The template config, like if it is HTML or PLAINTEXT';


INSERT INTO NTF_CUST_TMPL_APPLY
(ID, CODE, "DESC", CREATED_BY, CREATED_TIME, LAST_UPDATED_BY, LAST_UPDATED_TIME)
VALUES("SEQUENCE_NTF_CUST_TMPL_APPLY_ID"."NEXTVAL", 'CFS', 'CFS', 'SYSTEM', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP);

INSERT INTO NTF_CUST_TMPL_APPLY
(ID, CODE, "DESC", CREATED_BY, CREATED_TIME, LAST_UPDATED_BY, LAST_UPDATED_TIME)
VALUES("SEQUENCE_NTF_CUST_TMPL_APPLY_ID"."NEXTVAL", 'EMB', 'EMB', 'SYSTEM', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP);

INSERT INTO NTF_CUST_TMPL_APPLY
(ID, CODE, "DESC", CREATED_BY, CREATED_TIME, LAST_UPDATED_BY, LAST_UPDATED_TIME)
VALUES("SEQUENCE_NTF_CUST_TMPL_APPLY_ID"."NEXTVAL", 'GWB', 'GWB', 'SYSTEM', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP);

INSERT INTO NTF_CUST_TMPL_APPLY
(ID, CODE, "DESC", CREATED_BY, CREATED_TIME, LAST_UPDATED_BY, LAST_UPDATED_TIME)
VALUES("SEQUENCE_NTF_CUST_TMPL_APPLY_ID"."NEXTVAL", 'ALL', 'ALL bank customers', 'SYSTEM', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP);

-- NTF_TMPL_CHNL
INSERT INTO NTF_TMPL_CHNL
(ID, CHNL_TYPE, CHNL_NAME, CREATED_BY, CREATED_TIME, LAST_UPDATED_BY, LAST_UPDATED_TIME)
VALUES("SEQUENCE_NTF_TMPL_CHNL_ID"."NEXTVAL", 'EMAIL', 'Email', 'SYSTEM', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP);

INSERT INTO NTF_TMPL_CHNL
(ID, CHNL_TYPE, CHNL_NAME, CREATED_BY, CREATED_TIME, LAST_UPDATED_BY, LAST_UPDATED_TIME)
VALUES("SEQUENCE_NTF_TMPL_CHNL_ID"."NEXTVAL", 'SMS', 'SMS', 'SYSTEM', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP);

INSERT INTO NTF_TMPL_CHNL
(ID, CHNL_TYPE, CHNL_NAME, CREATED_BY, CREATED_TIME, LAST_UPDATED_BY, LAST_UPDATED_TIME)
VALUES("SEQUENCE_NTF_TMPL_CHNL_ID"."NEXTVAL", 'PUSHALERT', 'Push Alert', 'SYSTEM', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP);

-- NTF_TMPL_LNG
INSERT INTO NTF_TMPL_LNG
(ID, CODE, "DESC", CREATED_BY, CREATED_TIME, LAST_UPDATED_BY, LAST_UPDATED_TIME)
VALUES("SEQUENCE_NTF_TMPL_LNG_ID"."NEXTVAL", 'EN', 'English', 'SYSTEM', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP);

INSERT INTO NTF_TMPL_LNG
(ID, CODE, "DESC", CREATED_BY, CREATED_TIME, LAST_UPDATED_BY, LAST_UPDATED_TIME)
VALUES("SEQUENCE_NTF_TMPL_LNG_ID"."NEXTVAL", 'TC', 'Traditional Chinese', 'SYSTEM', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP);

INSERT INTO NTF_TMPL_LNG
(ID, CODE, "DESC", CREATED_BY, CREATED_TIME, LAST_UPDATED_BY, LAST_UPDATED_TIME)
VALUES("SEQUENCE_NTF_TMPL_LNG_ID"."NEXTVAL", 'SC', 'Simplified Chinese', 'SYSTEM', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP);

-- NTF_TMPL_TAG
INSERT INTO NTF_TMPL_TAG
(ID, NAME, CREATED_BY, CREATED_TIME, LAST_UPDATED_BY, LAST_UPDATED_TIME)
VALUES("SEQUENCE_NTF_TMPL_TAG_ID"."NEXTVAL", 'recipient', 'SYSTEM', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP);

INSERT INTO NTF_TMPL_TAG
(ID, NAME, CREATED_BY, CREATED_TIME, LAST_UPDATED_BY, LAST_UPDATED_TIME)
VALUES("SEQUENCE_NTF_TMPL_TAG_ID"."NEXTVAL", 'taskType', 'SYSTEM', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP);

INSERT INTO NTF_TMPL_TAG
(ID, NAME, CREATED_BY, CREATED_TIME, LAST_UPDATED_BY, LAST_UPDATED_TIME)
VALUES("SEQUENCE_NTF_TMPL_TAG_ID"."NEXTVAL", 'taskId', 'SYSTEM', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP);

INSERT INTO NTF_TMPL_TAG
(ID, NAME, CREATED_BY, CREATED_TIME, LAST_UPDATED_BY, LAST_UPDATED_TIME)
VALUES("SEQUENCE_NTF_TMPL_TAG_ID"."NEXTVAL", 'transactionType', 'SYSTEM', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP);
