MASTER_KEY_PASSWORD: !var UATVault/EPV/HK_UAT_cruise-cbs/master_key/password
MASTER_KEY_LOCATION: !var:file conjur/secrets/common/keystores/ms-uat-master-keystore
DB_PASSWORD: !var UATVault/EPV/OCHK_UAT_comm-cbs/cbsohuat_db_pwd/password
FLYWAY_PASSWORD: !var UATVault/EPV/OCHK_UAT_comm-cbs/cbsohuat_db_pwd/password