DB_PASSWORD: !var PRDVault/EPV/A_OH_PRD_comm-cbs-ochk/CBSOHPRD1-com_notif_hdlr_oh-com_notif_hdlr_oh/password
FLY_PASSWORD: !var PRDVault/EPV/A_OH_PRD_CBSDPY/CBSOHPRD1_CBSDPY_OH/password
MASTER_KEY_LOCATION: !var:file conjur/secrets/common/keystores/prod-ms-master-keystore
MASTER_KEY_PASSWORD: !var PRDVault/EPV/HK_APP_comm-cbs-ochk/prod-ms-keystore/password
CONJUR_KAFKA_KEYSTORE: !var:file conjur/secrets/common/keystores/prod-ms-master-keystore
CONJUR_KAFKA_KEYSTORE_PASSWORD: !var PRDVault/EPV/HK_APP_comm-cbs-ochk/prod-ms-keystore/password
CONJUR_KAFKA_KEYTAB: !var:file conjur/secrets/keytab/comm-cbs-ochk/2740271-keytab