CREATE TABLE TB_MESSAGE_CONDITION_DEF(
    ID VARCHAR2(32) NOT NULL,
    LEGAL_ENTITY VARCHAR2(32) NOT NULL,
    SERVICE_CODE VARCHAR2(255) NOT NULL,
    SERVICE_SUB_CODE VARCHAR2(255),
    MESSAGE_TYPE VARCHAR2(255),
    CUSTOMER_TYPE VARCHAR2(255),
    TRANSACTION_CHANNEL_CODE VARCHAR2(255),
    CONDITION VARCHAR2(255),
    DEBIT_CREDIT_FLAG VARCHAR2(255),
    EVENT_TYPE_CODE VARCHAR2(255),
    NOTIFICATION_TOPIC VARCHAR2(255),
    NOTIFICATION_TYPE VARCHAR2(255),
    PAYLOAD CLOB,
    TELLER_NO VARCHAR2(50),
    CHECKER_NO VARCHAR2(50),
    APPROVER_NO VARCHAR2(50),
    STATUS_CD VARCHAR2(50),
    VERSION_NO INT,
    CREATED_BY VARCHAR2(255),
    CREATED_TIME DATE,
    UPDATED_BY VARCHAR2(255),
    UPDATED_TIME DATE
);

COMMENT ON TABLE TB_MESSAGE_CONDITION_DEF IS '消息条件定义表';
COMMENT ON COLUMN TB_MESSAGE_CONDITION_DEF.ID IS 'ID;主键';
COMMENT ON COLUMN TB_MESSAGE_CONDITION_DEF.LEGAL_ENTITY IS '实体号';
COMMENT ON COLUMN TB_MESSAGE_CONDITION_DEF.SERVICE_CODE IS '场景号码';
COMMENT ON COLUMN TB_MESSAGE_CONDITION_DEF.SERVICE_SUB_CODE IS '子场景号码';
COMMENT ON COLUMN TB_MESSAGE_CONDITION_DEF.MESSAGE_TYPE IS '消息类型';
COMMENT ON COLUMN TB_MESSAGE_CONDITION_DEF.CUSTOMER_TYPE IS '客户类型';
COMMENT ON COLUMN TB_MESSAGE_CONDITION_DEF.TRANSACTION_CHANNEL_CODE IS '来源渠道码';
COMMENT ON COLUMN TB_MESSAGE_CONDITION_DEF.CONDITION IS '条件';
COMMENT ON COLUMN TB_MESSAGE_CONDITION_DEF.DEBIT_CREDIT_FLAG IS '借贷标志';
COMMENT ON COLUMN TB_MESSAGE_CONDITION_DEF.EVENT_TYPE_CODE IS '事件类型号码';
COMMENT ON COLUMN TB_MESSAGE_CONDITION_DEF.NOTIFICATION_TOPIC IS '消息主题';
COMMENT ON COLUMN TB_MESSAGE_CONDITION_DEF.NOTIFICATION_TYPE IS '消息类型';
COMMENT ON COLUMN TB_MESSAGE_CONDITION_DEF.PAYLOAD IS '消息主体';
COMMENT ON COLUMN TB_MESSAGE_CONDITION_DEF.TELLER_NO IS '操作员';
COMMENT ON COLUMN TB_MESSAGE_CONDITION_DEF.CHECKER_NO IS '复核员';
COMMENT ON COLUMN TB_MESSAGE_CONDITION_DEF.APPROVER_NO IS '审核员';
COMMENT ON COLUMN TB_MESSAGE_CONDITION_DEF.STATUS_CD IS '状态';
COMMENT ON COLUMN TB_MESSAGE_CONDITION_DEF.VERSION_NO IS '版本号';
COMMENT ON COLUMN TB_MESSAGE_CONDITION_DEF.CREATED_BY IS '创建人';
COMMENT ON COLUMN TB_MESSAGE_CONDITION_DEF.CREATED_TIME IS '创建时间';
COMMENT ON COLUMN TB_MESSAGE_CONDITION_DEF.UPDATED_BY IS '更新人';
COMMENT ON COLUMN TB_MESSAGE_CONDITION_DEF.UPDATED_TIME IS '更新时间';

CREATE TABLE TB_MESSAGE_CONSUMER_REG(
    ID VARCHAR2(32) NOT NULL,
    LEGAL_ENTITY VARCHAR2(32),
    SERVICE_CODE VARCHAR2(255),
    SERVICE_SUB_CODE VARCHAR2(255),
    PAYLOAD CLOB,
    CREATED_BY VARCHAR2(255),
    CREATED_TIME DATE,
    UPDATED_BY VARCHAR2(255),
    UPDATED_TIME DATE,
    PRIMARY KEY (ID)
);

COMMENT ON TABLE TB_MESSAGE_CONSUMER_REG IS '收取消息流水明细';
COMMENT ON COLUMN TB_MESSAGE_CONSUMER_REG.ID IS 'ID';
COMMENT ON COLUMN TB_MESSAGE_CONSUMER_REG.LEGAL_ENTITY IS '实体号';
COMMENT ON COLUMN TB_MESSAGE_CONSUMER_REG.SERVICE_CODE IS '场景号码';
COMMENT ON COLUMN TB_MESSAGE_CONSUMER_REG.SERVICE_SUB_CODE IS '子场景号码';
COMMENT ON COLUMN TB_MESSAGE_CONSUMER_REG.PAYLOAD IS '消息主题';
COMMENT ON COLUMN TB_MESSAGE_CONSUMER_REG.CREATED_BY IS '创建人';
COMMENT ON COLUMN TB_MESSAGE_CONSUMER_REG.CREATED_TIME IS '创建时间';
COMMENT ON COLUMN TB_MESSAGE_CONSUMER_REG.UPDATED_BY IS '更新人';
COMMENT ON COLUMN TB_MESSAGE_CONSUMER_REG.UPDATED_TIME IS '更新时间';

CREATE TABLE TB_MESSAGE_PRODUCER_REG(
    ID VARCHAR2(32) NOT NULL,
    CONSUMER_ID VARCHAR2(32),
    LEGAL_ENTITY VARCHAR2(32),
    NOTIFICATION_TOPIC VARCHAR2(255),
    EVENT_TYPE_CODE VARCHAR2(255),
    NOTIFICATION_TYPE VARCHAR2(255),
    PAYLOAD CLOB,
    CREATED_BY VARCHAR2(255),
    CREATED_TIME DATE,
    UPDATED_BY VARCHAR2(255),
    UPDATED_TIME DATE,
    PRIMARY KEY (ID)
);

COMMENT ON TABLE TB_MESSAGE_PRODUCER_REG IS '发送消息流水明细表';
COMMENT ON COLUMN TB_MESSAGE_PRODUCER_REG.ID IS 'ID';
COMMENT ON COLUMN TB_MESSAGE_PRODUCER_REG.CONSUMER_ID IS '发送ID';
COMMENT ON COLUMN TB_MESSAGE_PRODUCER_REG.LEGAL_ENTITY IS '实体号';
COMMENT ON COLUMN TB_MESSAGE_PRODUCER_REG.NOTIFICATION_TOPIC IS '消息主题';
COMMENT ON COLUMN TB_MESSAGE_PRODUCER_REG.EVENT_TYPE_CODE IS '事件类型号码';
COMMENT ON COLUMN TB_MESSAGE_PRODUCER_REG.NOTIFICATION_TYPE IS '消息类型';
COMMENT ON COLUMN TB_MESSAGE_PRODUCER_REG.PAYLOAD IS '消息主题';
COMMENT ON COLUMN TB_MESSAGE_PRODUCER_REG.CREATED_BY IS '创建人';
COMMENT ON COLUMN TB_MESSAGE_PRODUCER_REG.CREATED_TIME IS '创建时间';
COMMENT ON COLUMN TB_MESSAGE_PRODUCER_REG.UPDATED_BY IS '更新人';
COMMENT ON COLUMN TB_MESSAGE_PRODUCER_REG.UPDATED_TIME IS '更新时间';

create table SERVICE_CODE_TEMPLATE
(
    SERVICE_CODE   VARCHAR2(20)   not null,
    ALTER_TEMPLATE_CODE    VARCHAR2(100)  not null,
    NOTIFICATION_TEMPLATE_CODE   VARCHAR2(100)     not null,
    constraint SERVICE_CODE_TEMPLATE_PK
        primary key (SERVICE_CODE)
);



