MASTER_KEY_PASSWORD: !var UATVault/EPV/HK_UAT_cruise-cbs/master_key/password
MASTER_KEY_LOCATION: !var:file conjur/secrets/common/keystores/ms-uat-master-keystore
DB_PASSWORD: !var UATVault/EPV/HK_UAT_cruise-cbs/cbsohuat_db_pwd/password
FLYWAY_PASSWORD: !var UATVault/EPV/HK_UAT_cruise-cbs/cbsohuat_db_pwd/password
CONJUR_KAFKA_KEYTAB: !var:file conjur/secrets/keytab/comm-cbs-ochk/2097819-keytab
CONJUR_KAFKA_KEYSTORE: !var:file conjur/secrets/common/keystores/ms-uat-master-keystore
CONJUR_KAFKA_KEYSTORE_PASSWORD: !var UATVault/EPV/OCHK_UAT_comm-cbs/key-store-password/password